### PR TITLE
New document handler & v2 base routes

### PR DESCRIPTION
**Pull request by tnfAngel**
This adds a new document handler & adds v2 routes (base)

### CODE REVIEW

**Review by Mrgaton — CHANGES_REQUESTED** [review]
Save passowrds in sha256 or 384 or 512 maybe

**Comment by tnfAngel** [comment]
> Save passowrds in sha256 or 384 or 512 maybe

why not bcrypt

**Comment by Mrgaton** [comment]
I would put one that is fast and that is already buited into bun but well because in itself it does not have to be very secure in my opinion since if the files are stolen they can see the content without needing a password

**Comment by tnfAngel** [comment]
> I would put one that is fast and that is already buited into bun but well because in itself it does not have to be very secure in my opinion since if the files are stolen they can see the content without needing a password

is encryption really needed? the documents are not linked to users and the content will be visible, The only thing that would seem reasonable is that the content is also encrypted (using the password of the password-protected files?)

**Comment by tnfAngel** [comment]
Created an issue for this: https://github.com/JSPaste/JSP-Backend/issues/21

**Pull request merged**
